package modules

import controllers.crud.StudentScheduleAssociationCRUDController

trait StudentScheduleAssociationManagementModule {
  self: SemanticRepositoryModule with SecurityManagementModule =>
  def studentScheduleAssociationManagementController: StudentScheduleAssociationCRUDController
}

trait DefaultStudentScheduleAssociationManagementModuleImpl extends StudentScheduleAssociationManagementModule {
  self: SemanticRepositoryModule with BaseNamespace with SecurityManagementModule =>
  lazy val studentScheduleAssociationManagementController: StudentScheduleAssociationCRUDController = new StudentScheduleAssociationCRUDController(repository, namespace, roleService)
}
